# Generated by Django 5.0.1 on 2024-01-05 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mente_app', '0002_todolist_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 5, 14, 13, 0, 840394, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
            preserve_default=False,
        ),
    ]
