# Generated by Django 5.0.1 on 2024-01-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mente_app', '0003_todolist_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ('title',), 'verbose_name': 'Titulo', 'verbose_name_plural': 'Titulos'},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='data'),
        ),
    ]
