# Generated by Django 5.0.1 on 2024-01-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mente_app', '0004_alter_todolist_options_remove_todolist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
    ]
